### ISSUE TITLE
Clarification on Dual Signing Addresses for Hack Collection

### ISSUE THREAD

**Issue by mhxw** [metaplex-foundation/mpl-hybrid#4]
Hello @blockiosaurus ,

I've noticed that the hack collection uses two signing addresses: one user address and one admin address. Could you please confirm if this setup is correct? If it's not, what would be the appropriate way to handle this?

Looking forward to your response.

Thank you!

https://solscan.io/tx/5AdUKF9b68acGRZCBLiYuxZpzZE5e6h7t1dm6SxFKf66eJ1YsfwetpzTcQNW8xYmhrqBLPhdLVUVu7DswMS5M8gx

![image](https://github.com/user-attachments/assets/9e6a8768-6f50-4aa0-99bc-029afb5fc418)

**Comment by blockiosaurus** [comment]
Yes that is correct. The authority signer is giving the program permission to update the collection metadata and must be the same as the collection authority. However this requirement will be loosened in an upcoming release.
